apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: skdsz5k3y-dotnet-basic
  janus-idp.io/tekton: skdsz5k3y-dotnet-basic
  backstage.io/kubernetes-id: skdsz5k3y-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: skdsz5k3y-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
